{
  parserClass="com.feakin.intellij.parser.FkParser"
  parserUtilClass="com.intellij.lang.parser.GeneratedParserUtilBase"

  implements="com.feakin.intellij.psi.FkElement"
  extends="com.feakin.intellij.psi.impl.FkElementImpl"

  psiClassPrefix="Fk"
  psiImplClassSuffix="Impl"
  psiPackage="com.feakin.intellij.psi"
  psiImplPackage="com.feakin.intellij.psi.impl"

  elementTypeHolderClass="com.feakin.intellij.lexer.FkElementTypes"
  elementTypeClass="com.feakin.intellij.psi.impl.FkElementType"

  tokenTypeClass="com.feakin.intellij.lexer.FkTokenType"

  tokenTypeClass="com.feakin.intellij.lexer.FkTokenType"
  tokens = [
      COMMENT               = 'regexp://[^\r\n]*'
      BLOCK_COMMENT         = 'regexp:[/][*][^*]*[*]+([^/*][^*]*[*]+)*[/]'

      IDENTIFIER            = 'regexp:[_a-zA-Z][_a-zA-Z0-9]*'
      STRING_LITERAL        = "regexp:\"([^\\\"\r\n]|\\[^\r\n])*\"?"

      COMMA                 = ','
      COLON                 = ":"
      DOUBLE_COLON          = "::"
      SEMICOLON             = ";"
      LBRACE                = "{"
      RBRACE                = "}"
      EQUAL                 = "="
      QUOTA                 = "'"
      LPAREN                = '('
      RPAREN                = ')'
      LT                    =  '<'
      GT                    =  '>'
      DOT                   =  '.'
      RARROW                = "->"
      LARROW                = "<-"
      DARROW                = "<->"
      CONNECTION            = "--"

      CONTEXT_MAP_KEYWORD   = 'ContextMap'
      CONTEXT_KEYWORD       = 'Context'
      AGGREGATE_KEYWORD     = 'Aggregate'
      ENTITY_KEYWORD        = 'Entity'
      VALUE_OBJECT_KEYWORD  = 'ValueObject'
      STRUCT_KEYWORD        = 'Struct'
      IMPL_KEYWORD          = 'impl'
      ENDPOINT_KEYWORD      = 'endpoint'
      REQUEST_KEYWORD       = 'request'
      RESPONSE_KEYWORD      = 'response'

      GET_KEYWORD           = 'GET'
      POST_KEYWORD          = 'POST'
      PUT_KEYWORD           = 'PUT'
      DELETE_KEYWORD        = 'DELETE'
      PATCH_KEYWORD         = 'PATCH'
      HEAD_KEYWORD          = 'HEAD'
      OPTIONS_KEYWORD       = 'OPTIONS'
      AUTH_KEYWORD          = 'authorization'

      FLOW_KEYWORD          = 'flow'
      VIA_KEYWORD           = 'via'
      RECEIVE_KEYWORD       = 'receive'
      SEND_KEYWORD          = 'send'
      TO_KEYWORD            = 'to'
      FROM_KEYWORD          = 'from'
  ]


}

compilationUnit ::= declaration*

declaration ::= contextMapDeclaration
               | contextDeclaration
               | aggregateDeclaration
               | entityDeclaration
               | valueObjectDeclaration
               | structDeclaration
               | implDeclaration

contextMapDeclaration ::= CONTEXT_MAP_KEYWORD IDENTIFIER contextMapBody
{
  implements = [
    "com.feakin.intellij.psi.FkNamedElement"
    "com.feakin.intellij.psi.FkNameIdentifierOwner"
  ]
  mixin = "com.feakin.intellij.psi.ext.FkContextMapImplMixin"
  stubClass = "com.feakin.intellij.psi.stubs.FkContextMapDeclStub"
  elementTypeFactory = "com.feakin.intellij.psi.stubs.StubImplementationsKt.factory"
}

contextMapBody ::= LBRACE (contextNodeDecl | contextNodeRel)* RBRACE

private contextNodeDecl ::= CONTEXT_KEYWORD contextName (COMMA contextName)*

private contextNodeRel ::= leftContextNode relSymbol rightContextNode SEMICOLON

private leftContextNode ::= contextNodeName;

private rightContextNode ::= contextNodeName;

relSymbol ::= RARROW
             | LARROW
             | DARROW
             | CONNECTION
             ;

contextDeclaration ::= CONTEXT_KEYWORD IDENTIFIER contextBody {
  pin=1
}

contextBody ::= LBRACE useAggregate* RBRACE

aggregateDeclaration ::= AGGREGATE_KEYWORD IDENTIFIER aggregateBody {
  pin=1
}

entityDeclaration ::= ENTITY_KEYWORD IDENTIFIER entityBody {
  pin=1
}

valueObjectDeclaration ::= VALUE_OBJECT_KEYWORD IDENTIFIER valueObjectBody {
  pin=1
}

private useAggregate ::= AGGREGATE_KEYWORD IDENTIFIER (COMMA IDENTIFIER)* SEMICOLON

aggregateBody ::= LBRACE aggregateEntry* RBRACE

private aggregateEntry ::= useEntity

private useEntity ::= ENTITY_KEYWORD IDENTIFIER (COMMA IDENTIFIER)* SEMICOLON

entityBody ::= LBRACE (structDeclaration | useValueObject | useStruct)? RBRACE

structDeclaration ::= STRUCT_KEYWORD structBody {
  pin=1
  methods = [getName setName getNameIdentifier]
}

structBody ::= LBRACE structEntry* RBRACE

private structEntry ::= IDENTIFIER COLON fieldType defaultValue? SEMICOLON?

fieldType ::= IDENTIFIER ('<' IDENTIFIER '>')?
              ;

private defaultValue ::= EQUAL IDENTIFIER ('.' IDENTIFIER )?

private useValueObject ::= VALUE_OBJECT_KEYWORD IDENTIFIER (COMMA IDENTIFIER)? SEMICOLON
private useStruct      ::= STRUCT_KEYWORD IDENTIFIER (COMMA IDENTIFIER)? SEMICOLON

valueObjectBody ::= LBRACE (structDeclaration | useStruct)? RBRACE

implDeclaration ::= IMPL_KEYWORD IDENTIFIER implBody {
  pin=1
  methods = [getName setName getNameIdentifier]
}

implBody ::= LBRACE (endpointDeclaration flowDeclaration?)? RBRACE

endpointDeclaration ::= ENDPOINT_KEYWORD endpointBody

endpointBody ::= LBRACE requestDeclaration requestBody? authorizationDecl? responseDeclaration? RBRACE

private authorizationDecl ::= AUTH_KEYWORD COLON authorizationType? authorizationValue* SEMICOLON?

authorizationValue ::= IDENTIFIER
authorizationType ::= IDENTIFIER

requestDeclaration ::= httpRequestDeclaration

private httpRequestDeclaration ::= httpMethod uri SEMICOLON

httpMethod ::= GET_KEYWORD
              | POST_KEYWORD
              | PUT_KEYWORD
              | DELETE_KEYWORD
              | PATCH_KEYWORD
              | HEAD_KEYWORD
              | OPTIONS_KEYWORD
              ;

uri ::= STRING_LITERAL

requestBody ::= REQUEST_KEYWORD COLON (requestEntityName | structDeclaration) SEMICOLON;

responseDeclaration ::= RESPONSE_KEYWORD COLON responseEntityName SEMICOLON;

flowDeclaration ::= FLOW_KEYWORD flowBody

flowBody ::= LBRACE stepDeclaration* RBRACE

private stepDeclaration ::= viaMethodDeclaration
                     | viaMessageDeclaration

viaMethodDeclaration ::= VIA_KEYWORD objectName (DOUBLE_COLON viaMethodName parameters?)? RECEIVE_KEYWORD receiveObject SEMICOLON?

parameters ::= LPAREN parameter (COMMA parameter)* RPAREN

parameter ::= IDENTIFIER COLON paramType

paramType ::= IDENTIFIER ('<' IDENTIFIER '>')?
              ;

private receiveObject ::= objectName (COLON viaMethodName)?

viaMessageDeclaration ::= VIA_KEYWORD objectName SEND_KEYWORD passObject TO_KEYWORD topic SEMICOLON?

private passObject ::= objectName (COLON viaMethodName)?

topic ::= STRING_LITERAL

objectName ::= IDENTIFIER

viaMethodName ::= IDENTIFIER

requestEntityName ::= IDENTIFIER

responseEntityName ::= IDENTIFIER

contextName ::= IDENTIFIER

contextNodeName ::= IDENTIFIER
